### PR TITLE
Force ERB in Thor::Actions to use String buffer

### PR DESCRIPTION
**Pull request by k0kubun**
`#capture` depends on ERB's internal buffer. Since ERB's default buffer is changed to Array buffer in https://github.com/ruby/ruby/pull/1143, I fixed a buffer of Thor::Actions' erb to String buffer.

### CODE REVIEW

**Comment by yui-knk** [comment]
see [issue on Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/11842)

**Comment by yui-knk** [comment]
I think it is better to split first commit to another PR. The problem first commit will fix and the problem second commit will fix are differ.

**Comment by k0kubun** [comment]
> I think it is better to split first commit to another PR. The problem first commit will fix and the problem second commit will fix are differ.

I think so too. Done https://github.com/erikhuda/thor/pull/513.

**Comment by yui-knk** [comment]
:heart_eyes:

**Comment by sferik** [comment]
Thanks for making this change in advance of the Ruby 2.3 release. It looks like the build is passing without merging https://github.com/erikhuda/thor/pull/513. Can that be closed?

**Comment by k0kubun** [comment]
Thank you for merging this!

> It looks like the build is passing without merging #513. Can that be closed?

Not sure. While builds jobs are finished in https://travis-ci.org/erikhuda/thor/builds/97829708, a build for ruby-head (Ruby 2.3) haven't been finished yet https://travis-ci.org/erikhuda/thor/jobs/97829718. 

I guess it needs to update a test or implementation to finish all tests in Ruby 2.3.

**Pull request merged**
