### PR TITLE
Lazy-load io/console to avoid activating the gem unecessarily

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
Ping on getting this reviewed? Thanks!

**Comment by piotrmurach** [comment]
Hey, have you found it to be performance issue? I'm curious to see whether hiding file dependency in the bowels of codebase is good enough tradeoff?

**Comment by rafaelfranca** [comment]
The main reason to lazy loading it is that it is being extracted to a gem in Ruby 2.4+ and it may not be present in a ruby installation. It also is only necessary if the ruby installation doesn't have readline.

This change does make sense. Thanks.

**Comment by segiddins** [comment]
Its not a performance issue, but rather an issue for bundler & other gems -- if io-console is eagerly loaded, then the user cannot control what version is used

**Comment by piotrmurach** [comment]
I'm asking cuz I'm in a similar boat relying on 'io-console' and in particular in changing echo mode. I guess I'm looking for a robust solution. For example, what will happen if you're running on Ruby 2.4 and `io-console` gem is not installed whether through bundler or rubygems? Will the application explode with `LoadError` when that particular branch is called?

**Comment by rafaelfranca** [comment]
Yeah, that is what would happen today. We can improve it though with a fallback.

**Pull request merged**
